/*
 * This file is autogenerated with bcop:
 * The Compiz option code generator
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */

#ifndef _RESIZEINFO_OPTIONS_H
#define _RESIZEINFO_OPTIONS_H

#ifndef _RESIZEINFO_OPTIONS_INTERNAL
#define getCompPluginInfo resizeinfoOptionsGetCompPluginInfo
#endif

CompPluginVTable *resizeinfoOptionsGetCompPluginInfo (void);

typedef enum
{
    ResizeinfoDisplayOptionAlwaysShow,
    ResizeinfoDisplayOptionNum
} ResizeinfoDisplayOptions;

typedef void (*resizeinfoDisplayOptionChangeNotifyProc) (CompDisplay *display, CompOption *opt, ResizeinfoDisplayOptions num);

CompOption *resizeinfoGetDisplayOption (CompDisplay *d, ResizeinfoDisplayOptions num);

typedef enum
{
    ResizeinfoScreenOptionNum
} ResizeinfoScreenOptions;

typedef void (*resizeinfoScreenOptionChangeNotifyProc) (CompScreen *screen, CompOption *opt, ResizeinfoScreenOptions num);

CompOption *resizeinfoGetScreenOption (CompScreen *s, ResizeinfoScreenOptions num);

Bool             resizeinfoGetAlwaysShow (CompDisplay *d);
CompOption *     resizeinfoGetAlwaysShowOption (CompDisplay *d);
void             resizeinfoSetAlwaysShowNotify (CompDisplay *d, resizeinfoDisplayOptionChangeNotifyProc notify);
            
#endif
