debian/65compiz_profile-on-session /etc/X11/Xsession.d
debian/profile_upgrades/*.upgrade usr/share/compizconfig/upgrades
debian/unity*.ini /etc/compizconfig/
postinst/convert-files/*.convert usr/lib/compiz/migration/
usr/bin/gtk-window-decorator
usr/lib/*/compizconfig/backends/libgsettings.so
usr/lib/*/libcompizconfig_gsettings_backend.so
usr/share/applications/compiz.desktop usr/share/gnome/wm-properties/
usr/share/glib-2.0/schemas/*.xml
usr/share/gnome-control-center
